### ISSUE TITLE
[4667] Problemas no envio de alguns reportes

### ISSUE THREAD

**Issue by victorbortollossi** [br-openinsurance/PortalColetaMetricas#6]
De ontem para hoje começamos a ter alguns problemas no envio de alguns reportes, recebendo status DISCARDED com mensagem de que o endpoint não está listado.

Dois dos casos foram:

Enviado: /open-insurance/insurance-patrimonial/v1/{policyId}/premium
Esperado: /open-insurance/insurance-patrimonial/v1/insurance-patrimonial/{policyId}/premium

Enviado: /open-insurance/consents/v1/
Esperado: /open-insurance/consents/v1/consents

De acordo com a OAS versão 1.0.2, no entanto, os endpoints aceitos são /open-insurance/insurance-patrimonial/v1/{policyId}/premium e /open-insurance/consents/v1/, iguais aos que estamos de fato enviando.

A OAS sofrerá atualizações para refletir um novo enum ou o comportamento da PCM voltará a ter o comportamento anterior?

**Comment by luiztridapallifcamara** [comment]
Foi feita uma atualização na documentação do PCM. Na versão 1.0.3, estamos aderentes conforme as atualizações das api's que estão disponíveis na Área dev. Logo, api's na versão antiga, devem ser transformadas para a versão nova para que funcione no PCM.

Nesse caso, a versão da documentação que está sendo usada (1.0.2) não é a que temos atualmente (1.0.3).
