### ISSUE TITLE
[4670] Erro de "unlisted endpoint"

### ISSUE THREAD

**Issue by victorbortollossi** [br-openinsurance/PortalColetaMetricas#7]
Estamos tomando erro de "unlisted endpoint" ao enviar reportes para os endpoints a seguir:

/open-insurance/insurance-acceptance-and-branches-abroad/v1/insurance-acceptance-and-branches-abroad/{policyId}/policy-info
/open-insurance/insurance-acceptance-and-branches-abroad/v1/insurance-acceptance-and-branches-abroad/{policyId}/premium

Na resposta, notamos que o enum esperado contém os endpoints:

/open-insurance/insurance-acceptance-and-branches-abroad/v1//insurance-acceptance-and-branches-abroad/{policyId}/policy-info
/open-insurance/insurance-acceptance-and-branches-abroad/v1//insurance-acceptance-and-branches-abroad/{policyId}/premium

Portanto, essa barra adicional após v1 (v1//) deveria mesmo existir? 
Parece que houve algum equívoco na codificação e a barra foi duplicada para estes cenários, é isso mesmo?

**Comment by luiztridapallifcamara** [comment]
Não deveria ter a barra duplicada, ontem mesmo foi lançada uma hotfix para corrigir isso.
